version: '3.8'
name: 'build'
services: 
  create-certs:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /export
    entrypoint: 
      - /bin/sh
    command: /scripts/create-certs.sh